### ISSUE TITLE
The crawler is not working

### ISSUE THREAD

**Issue by shortymc** [ItsRRM97/Search-Engine#1]
Hello, i come because i got problem for use your script
the database search working but i don't know how use the crawler.php file

Can you help me ?
crawler.php
 `Connected Successfully Array ( ) `
the search engine is ther
http://www.tradezone.fr/tst/p/1search/

 Thanks for your great works,
best regards
shorty

**Comment by ItsRRM97** [comment]
Hi Shorty,

I'm sorry I took so long to answer your issue.
The Crawler is designed to simply crawl the URL and insert it into the database. So if you are using something like phpmyadmin I recommend you to take a look there. If that doesn't help simply comment the code where I am inserting the crawled URL into the database and instead echo out the crawled URL.

If it still does not help, follow this tutorial which I myself followed to design the web crawler https://www.youtube.com/watch?v=E0K9-0COv-M

Thanks for Appreciating my work, glad it helped.

Sincerely,
Roshan Raj Mishra

**Comment by shortymc** [comment]
Hello,
thanks for your support

From the start
The search engine works fine for data already in database.

 Can i add a url to crawl when using the search engine ?
normally if it type an url inside the crawler go on the web, find, in and insert it inside the database ?
or i need to put all urls to crawl directly inside tables with phpmy admin ? 

Best regards.
thanks for your great work

**Comment by ItsRRM97** [comment]
Yes, if you take a look at the crawler.php file there is a variable $start which points to a test.html file in its directory. I suggest you create a test.html file and specify the path there. Note that the test.html file should contain HTML achor tags with URLs you want the crawler to crawl. The crawler will automatically crawl the URL and all the sublinks and hyperlinks and insert it into the database. The process will continue until you stop the crawler.

Hope I was able to help you with this!
Roshan Raj Mishra

**Comment by shortymc** [comment]
Thanks for your help.
i made many attemps 
http://www.mapublicitegratuite.com/tst/1search/crawler.php
the scrapper take only the domain url where the script is inside.
ONLY THE HOSTING URL WORKS !
it's working fine but i can't see special characters , maybe a promlem with utf8-encode / utf8-decode
 I want to add url from other domains. you tell me normally it should works. It's works on the domain server but not for other domains. the script can't add other domains, but the script is online so i don't understand why its not working.
so i add 3 domains i use got inside the database, but not able to put another,
can you help me ?
http://www.mapublicitegratuite.com/tst/1search/test.html

 Can you help me ?
  
 Best regards
Thanks for your personnal invest in open source

**Comment by ItsRRM97** [comment]
Hi,

From what I see you have used the anchor tags incorrectly.
please use `<a href="https://www.gmail.com">Gmail</a>` and `<a href="http://www.telecharger.com">Telecharger</a>` and see if this works
